/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 111
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_service = 1,
  anon_sym_LBRACE = 2,
  anon_sym_operations = 3,
  anon_sym_COLON = 4,
  anon_sym_LBRACK = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACK = 7,
  anon_sym_RBRACE = 8,
  anon_sym_operation = 9,
  anon_sym_input = 10,
  anon_sym_output = 11,
  anon_sym_error = 12,
  anon_sym_struct = 13,
  anon_sym_enum = 14,
  aux_sym_ident_token1 = 15,
  anon_sym_option = 16,
  anon_sym_LT = 17,
  anon_sym_GT = 18,
  anon_sym_map = 19,
  sym_comment = 20,
  sym_doc = 21,
  sym_file = 22,
  sym__item = 23,
  sym_service = 24,
  sym_operation = 25,
  sym_input = 26,
  sym_output = 27,
  sym_error = 28,
  sym_struct = 29,
  sym_field = 30,
  sym_enum = 31,
  sym_variant = 32,
  sym_ident = 33,
  sym_type = 34,
  aux_sym_file_repeat1 = 35,
  aux_sym__item_repeat1 = 36,
  aux_sym_service_repeat1 = 37,
  aux_sym_operation_repeat1 = 38,
  aux_sym_struct_repeat1 = 39,
  aux_sym_enum_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_service] = "service",
  [anon_sym_LBRACE] = "{",
  [anon_sym_operations] = "operations",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_RBRACE] = "}",
  [anon_sym_operation] = "operation",
  [anon_sym_input] = "input",
  [anon_sym_output] = "output",
  [anon_sym_error] = "error",
  [anon_sym_struct] = "struct",
  [anon_sym_enum] = "enum",
  [aux_sym_ident_token1] = "ident_token1",
  [anon_sym_option] = "option",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_map] = "map",
  [sym_comment] = "comment",
  [sym_doc] = "doc",
  [sym_file] = "file",
  [sym__item] = "_item",
  [sym_service] = "service",
  [sym_operation] = "operation",
  [sym_input] = "input",
  [sym_output] = "output",
  [sym_error] = "error",
  [sym_struct] = "struct",
  [sym_field] = "field",
  [sym_enum] = "enum",
  [sym_variant] = "variant",
  [sym_ident] = "ident",
  [sym_type] = "type",
  [aux_sym_file_repeat1] = "file_repeat1",
  [aux_sym__item_repeat1] = "_item_repeat1",
  [aux_sym_service_repeat1] = "service_repeat1",
  [aux_sym_operation_repeat1] = "operation_repeat1",
  [aux_sym_struct_repeat1] = "struct_repeat1",
  [aux_sym_enum_repeat1] = "enum_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_service] = anon_sym_service,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_operations] = anon_sym_operations,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_operation] = anon_sym_operation,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_output] = anon_sym_output,
  [anon_sym_error] = anon_sym_error,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_enum] = anon_sym_enum,
  [aux_sym_ident_token1] = aux_sym_ident_token1,
  [anon_sym_option] = anon_sym_option,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_map] = anon_sym_map,
  [sym_comment] = sym_comment,
  [sym_doc] = sym_doc,
  [sym_file] = sym_file,
  [sym__item] = sym__item,
  [sym_service] = sym_service,
  [sym_operation] = sym_operation,
  [sym_input] = sym_input,
  [sym_output] = sym_output,
  [sym_error] = sym_error,
  [sym_struct] = sym_struct,
  [sym_field] = sym_field,
  [sym_enum] = sym_enum,
  [sym_variant] = sym_variant,
  [sym_ident] = sym_ident,
  [sym_type] = sym_type,
  [aux_sym_file_repeat1] = aux_sym_file_repeat1,
  [aux_sym__item_repeat1] = aux_sym__item_repeat1,
  [aux_sym_service_repeat1] = aux_sym_service_repeat1,
  [aux_sym_operation_repeat1] = aux_sym_operation_repeat1,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
  [aux_sym_enum_repeat1] = aux_sym_enum_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_service] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_operations] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_operation] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_output] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_error] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_ident_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_option] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_map] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_doc] = {
    .visible = true,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_service] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [sym_output] = {
    .visible = true,
    .named = true,
  },
  [sym_error] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_service_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 31,
  [39] = 39,
  [40] = 29,
  [41] = 41,
  [42] = 42,
  [43] = 30,
  [44] = 44,
  [45] = 27,
  [46] = 46,
  [47] = 47,
  [48] = 29,
  [49] = 30,
  [50] = 27,
  [51] = 31,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 26,
  [61] = 47,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 81,
  [91] = 72,
  [92] = 78,
  [93] = 81,
  [94] = 72,
  [95] = 78,
  [96] = 83,
  [97] = 82,
  [98] = 77,
  [99] = 83,
  [100] = 82,
  [101] = 77,
  [102] = 85,
  [103] = 73,
  [104] = 85,
  [105] = 73,
  [106] = 84,
  [107] = 84,
  [108] = 108,
  [109] = 108,
  [110] = 108,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        ',', 63,
        '/', 3,
        ':', 61,
        '<', 80,
        '>', 81,
        '[', 62,
        ']', 64,
        'e', 21,
        'i', 22,
        'm', 7,
        'o', 32,
        's', 13,
        '{', 59,
        '}', 65,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ',') ADVANCE(63);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '}') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 2:
      if (lookahead == ',') ADVANCE(63);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '[') ADVANCE(62);
      if (lookahead == ']') ADVANCE(64);
      if (lookahead == 'm') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(84);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(85);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(47);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(46);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(40);
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(71);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(50);
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(78);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(82);
      END_STATE();
    case 31:
      if (lookahead == 'p') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(14);
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(52);
      END_STATE();
    case 34:
      if (lookahead == 'p') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'p') ADVANCE(53);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(69);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(70);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 50:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 51:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(44);
      END_STATE();
    case 53:
      if (lookahead == 'u') ADVANCE(45);
      END_STATE();
    case 54:
      if (lookahead == 'v') ADVANCE(17);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 56:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        ',', 63,
        '/', 4,
        ':', 61,
        '<', 80,
        '>', 81,
        '[', 62,
        ']', 64,
        'e', 36,
        'i', 22,
        'o', 34,
        '{', 59,
        '}', 65,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_service);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_operations);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_operation);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_output);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_error);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (lookahead == 'i') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (lookahead == 'n') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (lookahead == 'o') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (lookahead == 'p') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (lookahead == 't') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_option);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_option);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_map);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_map);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '/') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_doc);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(86);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 56},
  [6] = {.lex_state = 56},
  [7] = {.lex_state = 56},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 56},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 56},
  [41] = {.lex_state = 56},
  [42] = {.lex_state = 56},
  [43] = {.lex_state = 56},
  [44] = {.lex_state = 56},
  [45] = {.lex_state = 56},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 56},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 56},
  [67] = {.lex_state = 56},
  [68] = {.lex_state = 56},
  [69] = {.lex_state = 56},
  [70] = {.lex_state = 56},
  [71] = {.lex_state = 56},
  [72] = {.lex_state = 56},
  [73] = {.lex_state = 56},
  [74] = {.lex_state = 56},
  [75] = {.lex_state = 56},
  [76] = {.lex_state = 56},
  [77] = {.lex_state = 5},
  [78] = {.lex_state = 56},
  [79] = {.lex_state = 56},
  [80] = {.lex_state = 56},
  [81] = {.lex_state = 56},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 5},
  [84] = {.lex_state = 5},
  [85] = {.lex_state = 56},
  [86] = {.lex_state = 56},
  [87] = {.lex_state = 56},
  [88] = {.lex_state = 56},
  [89] = {.lex_state = 56},
  [90] = {.lex_state = 56},
  [91] = {.lex_state = 56},
  [92] = {.lex_state = 56},
  [93] = {.lex_state = 56},
  [94] = {.lex_state = 56},
  [95] = {.lex_state = 56},
  [96] = {.lex_state = 5},
  [97] = {.lex_state = 5},
  [98] = {.lex_state = 5},
  [99] = {.lex_state = 5},
  [100] = {.lex_state = 5},
  [101] = {.lex_state = 5},
  [102] = {.lex_state = 56},
  [103] = {.lex_state = 56},
  [104] = {.lex_state = 56},
  [105] = {.lex_state = 56},
  [106] = {.lex_state = 5},
  [107] = {.lex_state = 5},
  [108] = {.lex_state = 56},
  [109] = {.lex_state = 56},
  [110] = {.lex_state = 56},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_service] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_operation] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_output] = ACTIONS(1),
    [anon_sym_error] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_option] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_map] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_doc] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_file] = STATE(87),
    [sym__item] = STATE(2),
    [sym_service] = STATE(2),
    [sym_operation] = STATE(2),
    [sym_struct] = STATE(2),
    [sym_enum] = STATE(2),
    [aux_sym_file_repeat1] = STATE(2),
    [aux_sym__item_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_service] = ACTIONS(7),
    [anon_sym_operation] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(11),
    [anon_sym_enum] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [sym_doc] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_service,
    ACTIONS(9), 1,
      anon_sym_operation,
    ACTIONS(11), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_enum,
    ACTIONS(15), 1,
      sym_doc,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      aux_sym__item_repeat1,
    STATE(3), 6,
      sym__item,
      sym_service,
      sym_operation,
      sym_struct,
      sym_enum,
      aux_sym_file_repeat1,
  [33] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_service,
    ACTIONS(24), 1,
      anon_sym_operation,
    ACTIONS(27), 1,
      anon_sym_struct,
    ACTIONS(30), 1,
      anon_sym_enum,
    ACTIONS(33), 1,
      sym_doc,
    STATE(4), 1,
      aux_sym__item_repeat1,
    STATE(3), 6,
      sym__item,
      sym_service,
      sym_operation,
      sym_struct,
      sym_enum,
      aux_sym_file_repeat1,
  [66] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_service,
    ACTIONS(9), 1,
      anon_sym_operation,
    ACTIONS(11), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_enum,
    ACTIONS(36), 1,
      sym_doc,
    STATE(26), 1,
      aux_sym__item_repeat1,
    STATE(18), 4,
      sym_service,
      sym_operation,
      sym_struct,
      sym_enum,
  [94] = 6,
    ACTIONS(38), 1,
      anon_sym_RBRACE,
    ACTIONS(40), 1,
      anon_sym_input,
    ACTIONS(42), 1,
      anon_sym_output,
    ACTIONS(44), 1,
      anon_sym_error,
    ACTIONS(46), 1,
      sym_comment,
    STATE(6), 4,
      sym_input,
      sym_output,
      sym_error,
      aux_sym_operation_repeat1,
  [116] = 6,
    ACTIONS(40), 1,
      anon_sym_input,
    ACTIONS(42), 1,
      anon_sym_output,
    ACTIONS(44), 1,
      anon_sym_error,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    STATE(7), 4,
      sym_input,
      sym_output,
      sym_error,
      aux_sym_operation_repeat1,
  [138] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    ACTIONS(52), 1,
      anon_sym_input,
    ACTIONS(55), 1,
      anon_sym_output,
    ACTIONS(58), 1,
      anon_sym_error,
    STATE(7), 4,
      sym_input,
      sym_output,
      sym_error,
      aux_sym_operation_repeat1,
  [160] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    ACTIONS(63), 1,
      aux_sym_ident_token1,
    ACTIONS(66), 1,
      sym_doc,
    STATE(53), 1,
      aux_sym__item_repeat1,
    STATE(54), 1,
      sym_ident,
    STATE(8), 2,
      sym_variant,
      aux_sym_enum_repeat1,
  [183] = 8,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(72), 1,
      anon_sym_RBRACK,
    ACTIONS(74), 1,
      aux_sym_ident_token1,
    ACTIONS(77), 1,
      anon_sym_option,
    ACTIONS(80), 1,
      anon_sym_map,
    STATE(9), 1,
      aux_sym_service_repeat1,
    STATE(24), 1,
      sym_type,
  [208] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 1,
      aux_sym_ident_token1,
    ACTIONS(87), 1,
      sym_doc,
    STATE(55), 1,
      aux_sym__item_repeat1,
    STATE(79), 1,
      sym_ident,
    STATE(12), 2,
      sym_field,
      aux_sym_struct_repeat1,
  [231] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    ACTIONS(91), 1,
      aux_sym_ident_token1,
    ACTIONS(93), 1,
      sym_doc,
    STATE(53), 1,
      aux_sym__item_repeat1,
    STATE(54), 1,
      sym_ident,
    STATE(8), 2,
      sym_variant,
      aux_sym_enum_repeat1,
  [254] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    ACTIONS(97), 1,
      aux_sym_ident_token1,
    ACTIONS(100), 1,
      sym_doc,
    STATE(55), 1,
      aux_sym__item_repeat1,
    STATE(79), 1,
      sym_ident,
    STATE(12), 2,
      sym_field,
      aux_sym_struct_repeat1,
  [277] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_ident_token1,
    ACTIONS(87), 1,
      sym_doc,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym__item_repeat1,
    STATE(79), 1,
      sym_ident,
    STATE(10), 2,
      sym_field,
      aux_sym_struct_repeat1,
  [300] = 8,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LBRACK,
    ACTIONS(107), 1,
      anon_sym_RBRACK,
    ACTIONS(109), 1,
      aux_sym_ident_token1,
    ACTIONS(111), 1,
      anon_sym_option,
    ACTIONS(113), 1,
      anon_sym_map,
    STATE(16), 1,
      aux_sym_service_repeat1,
    STATE(24), 1,
      sym_type,
  [325] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      aux_sym_ident_token1,
    ACTIONS(93), 1,
      sym_doc,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      aux_sym__item_repeat1,
    STATE(54), 1,
      sym_ident,
    STATE(11), 2,
      sym_variant,
      aux_sym_enum_repeat1,
  [348] = 8,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      aux_sym_ident_token1,
    ACTIONS(111), 1,
      anon_sym_option,
    ACTIONS(113), 1,
      anon_sym_map,
    ACTIONS(117), 1,
      anon_sym_RBRACK,
    STATE(9), 1,
      aux_sym_service_repeat1,
    STATE(24), 1,
      sym_type,
  [373] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [397] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [409] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [433] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [457] = 4,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(133), 2,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(137), 3,
      aux_sym_ident_token1,
      anon_sym_option,
      anon_sym_map,
  [473] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [485] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_doc,
    STATE(26), 1,
      aux_sym__item_repeat1,
    ACTIONS(141), 4,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
  [501] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(146), 3,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(148), 3,
      aux_sym_ident_token1,
      anon_sym_option,
      anon_sym_map,
  [515] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [527] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(152), 3,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(154), 3,
      aux_sym_ident_token1,
      anon_sym_option,
      anon_sym_map,
  [541] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(156), 3,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(158), 3,
      aux_sym_ident_token1,
      anon_sym_option,
      anon_sym_map,
  [555] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(160), 3,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(162), 3,
      aux_sym_ident_token1,
      anon_sym_option,
      anon_sym_map,
  [569] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_LBRACK,
    ACTIONS(166), 1,
      aux_sym_ident_token1,
    ACTIONS(168), 1,
      anon_sym_option,
    ACTIONS(170), 1,
      anon_sym_map,
    STATE(42), 1,
      sym_type,
  [588] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_LBRACK,
    ACTIONS(166), 1,
      aux_sym_ident_token1,
    ACTIONS(168), 1,
      anon_sym_option,
    ACTIONS(170), 1,
      anon_sym_map,
    STATE(44), 1,
      sym_type,
  [607] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_LBRACK,
    ACTIONS(174), 1,
      aux_sym_ident_token1,
    ACTIONS(176), 1,
      anon_sym_option,
    ACTIONS(178), 1,
      anon_sym_map,
    STATE(46), 1,
      sym_type,
  [626] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_LBRACK,
    ACTIONS(174), 1,
      aux_sym_ident_token1,
    ACTIONS(176), 1,
      anon_sym_option,
    ACTIONS(178), 1,
      anon_sym_map,
    STATE(39), 1,
      sym_type,
  [645] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(72), 2,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(180), 3,
      aux_sym_ident_token1,
      anon_sym_option,
      anon_sym_map,
  [658] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_LBRACK,
    ACTIONS(166), 1,
      aux_sym_ident_token1,
    ACTIONS(168), 1,
      anon_sym_option,
    ACTIONS(170), 1,
      anon_sym_map,
    STATE(41), 1,
      sym_type,
  [677] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(160), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [687] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(184), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [699] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(152), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [709] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(186), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [719] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(188), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [729] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(156), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [739] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(190), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [749] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(146), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [759] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(194), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [771] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [781] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [791] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [801] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [811] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [821] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(200), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [833] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      aux_sym_ident_token1,
    ACTIONS(202), 1,
      sym_doc,
    STATE(52), 1,
      sym_ident,
    STATE(60), 1,
      aux_sym__item_repeat1,
  [849] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    ACTIONS(206), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [861] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_ident_token1,
    ACTIONS(202), 1,
      sym_doc,
    STATE(60), 1,
      aux_sym__item_repeat1,
    STATE(68), 1,
      sym_ident,
  [877] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [886] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [895] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [904] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [913] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      aux_sym_ident_token1,
    ACTIONS(212), 1,
      sym_doc,
    STATE(60), 1,
      aux_sym__item_repeat1,
  [926] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(196), 2,
      anon_sym_LBRACE,
      anon_sym_COLON,
  [934] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_ident_token1,
    STATE(71), 1,
      sym_ident,
  [944] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_ident_token1,
    STATE(76), 1,
      sym_ident,
  [954] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_ident_token1,
    STATE(66), 1,
      sym_ident,
  [964] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_ident_token1,
    STATE(75), 1,
      sym_ident,
  [974] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_LBRACE,
  [981] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_COLON,
  [988] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_COLON,
  [995] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
  [1002] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_COLON,
  [1009] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
  [1016] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_GT,
  [1023] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_COMMA,
  [1030] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_COLON,
  [1037] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
  [1044] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
  [1051] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(237), 1,
      aux_sym_ident_token1,
  [1058] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_GT,
  [1065] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_COLON,
  [1072] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_LBRACK,
  [1079] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_RBRACK,
  [1086] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(247), 1,
      aux_sym_ident_token1,
  [1093] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(249), 1,
      aux_sym_ident_token1,
  [1100] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(251), 1,
      aux_sym_ident_token1,
  [1107] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_LT,
  [1114] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_COLON,
  [1121] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
  [1128] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_operations,
  [1135] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_RBRACE,
  [1142] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_RBRACK,
  [1149] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_GT,
  [1156] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_GT,
  [1163] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_RBRACK,
  [1170] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_GT,
  [1177] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_GT,
  [1184] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(275), 1,
      aux_sym_ident_token1,
  [1191] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(277), 1,
      aux_sym_ident_token1,
  [1198] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(279), 1,
      aux_sym_ident_token1,
  [1205] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(281), 1,
      aux_sym_ident_token1,
  [1212] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(283), 1,
      aux_sym_ident_token1,
  [1219] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(285), 1,
      aux_sym_ident_token1,
  [1226] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_LT,
  [1233] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_COMMA,
  [1240] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_LT,
  [1247] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_COMMA,
  [1254] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(295), 1,
      aux_sym_ident_token1,
  [1261] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(297), 1,
      aux_sym_ident_token1,
  [1268] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_LT,
  [1275] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_LT,
  [1282] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_LT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 94,
  [SMALL_STATE(6)] = 116,
  [SMALL_STATE(7)] = 138,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 183,
  [SMALL_STATE(10)] = 208,
  [SMALL_STATE(11)] = 231,
  [SMALL_STATE(12)] = 254,
  [SMALL_STATE(13)] = 277,
  [SMALL_STATE(14)] = 300,
  [SMALL_STATE(15)] = 325,
  [SMALL_STATE(16)] = 348,
  [SMALL_STATE(17)] = 373,
  [SMALL_STATE(18)] = 385,
  [SMALL_STATE(19)] = 397,
  [SMALL_STATE(20)] = 409,
  [SMALL_STATE(21)] = 421,
  [SMALL_STATE(22)] = 433,
  [SMALL_STATE(23)] = 445,
  [SMALL_STATE(24)] = 457,
  [SMALL_STATE(25)] = 473,
  [SMALL_STATE(26)] = 485,
  [SMALL_STATE(27)] = 501,
  [SMALL_STATE(28)] = 515,
  [SMALL_STATE(29)] = 527,
  [SMALL_STATE(30)] = 541,
  [SMALL_STATE(31)] = 555,
  [SMALL_STATE(32)] = 569,
  [SMALL_STATE(33)] = 588,
  [SMALL_STATE(34)] = 607,
  [SMALL_STATE(35)] = 626,
  [SMALL_STATE(36)] = 645,
  [SMALL_STATE(37)] = 658,
  [SMALL_STATE(38)] = 677,
  [SMALL_STATE(39)] = 687,
  [SMALL_STATE(40)] = 699,
  [SMALL_STATE(41)] = 709,
  [SMALL_STATE(42)] = 719,
  [SMALL_STATE(43)] = 729,
  [SMALL_STATE(44)] = 739,
  [SMALL_STATE(45)] = 749,
  [SMALL_STATE(46)] = 759,
  [SMALL_STATE(47)] = 771,
  [SMALL_STATE(48)] = 781,
  [SMALL_STATE(49)] = 791,
  [SMALL_STATE(50)] = 801,
  [SMALL_STATE(51)] = 811,
  [SMALL_STATE(52)] = 821,
  [SMALL_STATE(53)] = 833,
  [SMALL_STATE(54)] = 849,
  [SMALL_STATE(55)] = 861,
  [SMALL_STATE(56)] = 877,
  [SMALL_STATE(57)] = 886,
  [SMALL_STATE(58)] = 895,
  [SMALL_STATE(59)] = 904,
  [SMALL_STATE(60)] = 913,
  [SMALL_STATE(61)] = 926,
  [SMALL_STATE(62)] = 934,
  [SMALL_STATE(63)] = 944,
  [SMALL_STATE(64)] = 954,
  [SMALL_STATE(65)] = 964,
  [SMALL_STATE(66)] = 974,
  [SMALL_STATE(67)] = 981,
  [SMALL_STATE(68)] = 988,
  [SMALL_STATE(69)] = 995,
  [SMALL_STATE(70)] = 1002,
  [SMALL_STATE(71)] = 1009,
  [SMALL_STATE(72)] = 1016,
  [SMALL_STATE(73)] = 1023,
  [SMALL_STATE(74)] = 1030,
  [SMALL_STATE(75)] = 1037,
  [SMALL_STATE(76)] = 1044,
  [SMALL_STATE(77)] = 1051,
  [SMALL_STATE(78)] = 1058,
  [SMALL_STATE(79)] = 1065,
  [SMALL_STATE(80)] = 1072,
  [SMALL_STATE(81)] = 1079,
  [SMALL_STATE(82)] = 1086,
  [SMALL_STATE(83)] = 1093,
  [SMALL_STATE(84)] = 1100,
  [SMALL_STATE(85)] = 1107,
  [SMALL_STATE(86)] = 1114,
  [SMALL_STATE(87)] = 1121,
  [SMALL_STATE(88)] = 1128,
  [SMALL_STATE(89)] = 1135,
  [SMALL_STATE(90)] = 1142,
  [SMALL_STATE(91)] = 1149,
  [SMALL_STATE(92)] = 1156,
  [SMALL_STATE(93)] = 1163,
  [SMALL_STATE(94)] = 1170,
  [SMALL_STATE(95)] = 1177,
  [SMALL_STATE(96)] = 1184,
  [SMALL_STATE(97)] = 1191,
  [SMALL_STATE(98)] = 1198,
  [SMALL_STATE(99)] = 1205,
  [SMALL_STATE(100)] = 1212,
  [SMALL_STATE(101)] = 1219,
  [SMALL_STATE(102)] = 1226,
  [SMALL_STATE(103)] = 1233,
  [SMALL_STATE(104)] = 1240,
  [SMALL_STATE(105)] = 1247,
  [SMALL_STATE(106)] = 1254,
  [SMALL_STATE(107)] = 1261,
  [SMALL_STATE(108)] = 1268,
  [SMALL_STATE(109)] = 1275,
  [SMALL_STATE(110)] = 1282,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operation_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operation_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operation_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operation_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 9, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 5, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 5, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 4, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_service_repeat1, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 8, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__item_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__item_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 4, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 4, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 6, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 6, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ident, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 3, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 5, 0, 0),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__item_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [257] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lockstep(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lockstep",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
