/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 119
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_service = 1,
  anon_sym_LBRACE = 2,
  anon_sym_operations = 3,
  anon_sym_COLON = 4,
  anon_sym_LBRACK = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACK = 7,
  anon_sym_RBRACE = 8,
  anon_sym_operation = 9,
  anon_sym_input = 10,
  anon_sym_output = 11,
  anon_sym_error = 12,
  anon_sym_struct = 13,
  anon_sym_enum = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  aux_sym_ident_token1 = 17,
  anon_sym_option = 18,
  anon_sym_LT = 19,
  anon_sym_GT = 20,
  anon_sym_map = 21,
  sym_comment = 22,
  sym_doc = 23,
  sym_file = 24,
  sym__item = 25,
  sym_service = 26,
  sym_operation = 27,
  sym_input = 28,
  sym_output = 29,
  sym_error = 30,
  sym_struct = 31,
  sym_field = 32,
  sym_enum = 33,
  sym_variant = 34,
  sym_variant_fields = 35,
  sym_unnamed_fields = 36,
  sym_ident = 37,
  sym_type = 38,
  aux_sym_file_repeat1 = 39,
  aux_sym__item_repeat1 = 40,
  aux_sym_service_repeat1 = 41,
  aux_sym_operation_repeat1 = 42,
  aux_sym_struct_repeat1 = 43,
  aux_sym_enum_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_service] = "service",
  [anon_sym_LBRACE] = "{",
  [anon_sym_operations] = "operations",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_RBRACE] = "}",
  [anon_sym_operation] = "operation",
  [anon_sym_input] = "input",
  [anon_sym_output] = "output",
  [anon_sym_error] = "error",
  [anon_sym_struct] = "struct",
  [anon_sym_enum] = "enum",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_ident_token1] = "ident_token1",
  [anon_sym_option] = "option",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_map] = "map",
  [sym_comment] = "comment",
  [sym_doc] = "doc",
  [sym_file] = "file",
  [sym__item] = "_item",
  [sym_service] = "service",
  [sym_operation] = "operation",
  [sym_input] = "input",
  [sym_output] = "output",
  [sym_error] = "error",
  [sym_struct] = "struct",
  [sym_field] = "field",
  [sym_enum] = "enum",
  [sym_variant] = "variant",
  [sym_variant_fields] = "variant_fields",
  [sym_unnamed_fields] = "unnamed_fields",
  [sym_ident] = "ident",
  [sym_type] = "type",
  [aux_sym_file_repeat1] = "file_repeat1",
  [aux_sym__item_repeat1] = "_item_repeat1",
  [aux_sym_service_repeat1] = "service_repeat1",
  [aux_sym_operation_repeat1] = "operation_repeat1",
  [aux_sym_struct_repeat1] = "struct_repeat1",
  [aux_sym_enum_repeat1] = "enum_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_service] = anon_sym_service,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_operations] = anon_sym_operations,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_operation] = anon_sym_operation,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_output] = anon_sym_output,
  [anon_sym_error] = anon_sym_error,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_ident_token1] = aux_sym_ident_token1,
  [anon_sym_option] = anon_sym_option,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_map] = anon_sym_map,
  [sym_comment] = sym_comment,
  [sym_doc] = sym_doc,
  [sym_file] = sym_file,
  [sym__item] = sym__item,
  [sym_service] = sym_service,
  [sym_operation] = sym_operation,
  [sym_input] = sym_input,
  [sym_output] = sym_output,
  [sym_error] = sym_error,
  [sym_struct] = sym_struct,
  [sym_field] = sym_field,
  [sym_enum] = sym_enum,
  [sym_variant] = sym_variant,
  [sym_variant_fields] = sym_variant_fields,
  [sym_unnamed_fields] = sym_unnamed_fields,
  [sym_ident] = sym_ident,
  [sym_type] = sym_type,
  [aux_sym_file_repeat1] = aux_sym_file_repeat1,
  [aux_sym__item_repeat1] = aux_sym__item_repeat1,
  [aux_sym_service_repeat1] = aux_sym_service_repeat1,
  [aux_sym_operation_repeat1] = aux_sym_operation_repeat1,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
  [aux_sym_enum_repeat1] = aux_sym_enum_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_service] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_operations] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_operation] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_output] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_error] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_ident_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_option] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_map] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_doc] = {
    .visible = true,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_service] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [sym_output] = {
    .visible = true,
    .named = true,
  },
  [sym_error] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_variant_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_unnamed_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_service_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 22,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 24,
  [57] = 25,
  [58] = 23,
  [59] = 22,
  [60] = 23,
  [61] = 24,
  [62] = 25,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 33,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 40,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 74,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 88,
  [99] = 80,
  [100] = 86,
  [101] = 88,
  [102] = 80,
  [103] = 86,
  [104] = 94,
  [105] = 89,
  [106] = 85,
  [107] = 94,
  [108] = 89,
  [109] = 85,
  [110] = 110,
  [111] = 81,
  [112] = 74,
  [113] = 81,
  [114] = 90,
  [115] = 90,
  [116] = 79,
  [117] = 79,
  [118] = 118,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        '(', 72,
        ')', 73,
        ',', 63,
        '/', 2,
        ':', 61,
        '<', 82,
        '>', 83,
        '[', 62,
        ']', 64,
        'e', 21,
        'i', 22,
        'm', 7,
        'o', 32,
        's', 13,
        '{', 59,
        '}', 65,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(72);
      if (lookahead == ',') ADVANCE(63);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '}') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(86);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(87);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(34);
      if (lookahead == '}') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(47);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(46);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(40);
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(71);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(50);
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(84);
      END_STATE();
    case 31:
      if (lookahead == 'p') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(14);
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(52);
      END_STATE();
    case 34:
      if (lookahead == 'p') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'p') ADVANCE(53);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(69);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(70);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 50:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 51:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(44);
      END_STATE();
    case 53:
      if (lookahead == 'u') ADVANCE(45);
      END_STATE();
    case 54:
      if (lookahead == 'v') ADVANCE(17);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 56:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        ')', 73,
        ',', 63,
        '/', 3,
        ':', 61,
        '<', 82,
        '>', 83,
        '[', 62,
        ']', 64,
        'm', 6,
        'o', 31,
        '{', 59,
        '}', 65,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_service);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_operations);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_operation);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_output);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_error);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (lookahead == 'i') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (lookahead == 'n') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (lookahead == 'o') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (lookahead == 'p') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (lookahead == 't') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_option);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_option);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_map);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_map);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '/') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_doc);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 56},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 56},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 56},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 56},
  [20] = {.lex_state = 56},
  [21] = {.lex_state = 56},
  [22] = {.lex_state = 56},
  [23] = {.lex_state = 56},
  [24] = {.lex_state = 56},
  [25] = {.lex_state = 56},
  [26] = {.lex_state = 56},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 56},
  [38] = {.lex_state = 56},
  [39] = {.lex_state = 56},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 56},
  [42] = {.lex_state = 56},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 5},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 56},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 5},
  [74] = {.lex_state = 56},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 56},
  [77] = {.lex_state = 56},
  [78] = {.lex_state = 56},
  [79] = {.lex_state = 56},
  [80] = {.lex_state = 56},
  [81] = {.lex_state = 56},
  [82] = {.lex_state = 56},
  [83] = {.lex_state = 56},
  [84] = {.lex_state = 56},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 56},
  [87] = {.lex_state = 56},
  [88] = {.lex_state = 56},
  [89] = {.lex_state = 5},
  [90] = {.lex_state = 5},
  [91] = {.lex_state = 56},
  [92] = {.lex_state = 56},
  [93] = {.lex_state = 56},
  [94] = {.lex_state = 5},
  [95] = {.lex_state = 56},
  [96] = {.lex_state = 56},
  [97] = {.lex_state = 56},
  [98] = {.lex_state = 56},
  [99] = {.lex_state = 56},
  [100] = {.lex_state = 56},
  [101] = {.lex_state = 56},
  [102] = {.lex_state = 56},
  [103] = {.lex_state = 56},
  [104] = {.lex_state = 5},
  [105] = {.lex_state = 5},
  [106] = {.lex_state = 5},
  [107] = {.lex_state = 5},
  [108] = {.lex_state = 5},
  [109] = {.lex_state = 5},
  [110] = {.lex_state = 56},
  [111] = {.lex_state = 56},
  [112] = {.lex_state = 56},
  [113] = {.lex_state = 56},
  [114] = {.lex_state = 5},
  [115] = {.lex_state = 5},
  [116] = {.lex_state = 56},
  [117] = {.lex_state = 56},
  [118] = {.lex_state = 56},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_service] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_operation] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_output] = ACTIONS(1),
    [anon_sym_error] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_option] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_map] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_doc] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_file] = STATE(87),
    [sym__item] = STATE(2),
    [sym_service] = STATE(2),
    [sym_operation] = STATE(2),
    [sym_struct] = STATE(2),
    [sym_enum] = STATE(2),
    [aux_sym_file_repeat1] = STATE(2),
    [aux_sym__item_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_service] = ACTIONS(7),
    [anon_sym_operation] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(11),
    [anon_sym_enum] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [sym_doc] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_service,
    ACTIONS(9), 1,
      anon_sym_operation,
    ACTIONS(11), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_enum,
    ACTIONS(15), 1,
      sym_doc,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      aux_sym__item_repeat1,
    STATE(3), 6,
      sym__item,
      sym_service,
      sym_operation,
      sym_struct,
      sym_enum,
      aux_sym_file_repeat1,
  [33] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_service,
    ACTIONS(24), 1,
      anon_sym_operation,
    ACTIONS(27), 1,
      anon_sym_struct,
    ACTIONS(30), 1,
      anon_sym_enum,
    ACTIONS(33), 1,
      sym_doc,
    STATE(4), 1,
      aux_sym__item_repeat1,
    STATE(3), 6,
      sym__item,
      sym_service,
      sym_operation,
      sym_struct,
      sym_enum,
      aux_sym_file_repeat1,
  [66] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_service,
    ACTIONS(9), 1,
      anon_sym_operation,
    ACTIONS(11), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_enum,
    ACTIONS(36), 1,
      sym_doc,
    STATE(33), 1,
      aux_sym__item_repeat1,
    STATE(29), 4,
      sym_service,
      sym_operation,
      sym_struct,
      sym_enum,
  [94] = 8,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      aux_sym_ident_token1,
    ACTIONS(46), 1,
      anon_sym_option,
    ACTIONS(49), 1,
      anon_sym_map,
    ACTIONS(52), 1,
      sym_comment,
    STATE(5), 1,
      aux_sym_service_repeat1,
    STATE(21), 1,
      sym_type,
    ACTIONS(41), 2,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [120] = 6,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_RBRACE,
    ACTIONS(56), 1,
      anon_sym_input,
    ACTIONS(58), 1,
      anon_sym_output,
    ACTIONS(60), 1,
      anon_sym_error,
    STATE(7), 4,
      sym_input,
      sym_output,
      sym_error,
      aux_sym_operation_repeat1,
  [142] = 6,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    ACTIONS(64), 1,
      anon_sym_input,
    ACTIONS(67), 1,
      anon_sym_output,
    ACTIONS(70), 1,
      anon_sym_error,
    STATE(7), 4,
      sym_input,
      sym_output,
      sym_error,
      aux_sym_operation_repeat1,
  [164] = 6,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_input,
    ACTIONS(58), 1,
      anon_sym_output,
    ACTIONS(60), 1,
      anon_sym_error,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(6), 4,
      sym_input,
      sym_output,
      sym_error,
      aux_sym_operation_repeat1,
  [186] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    ACTIONS(77), 1,
      aux_sym_ident_token1,
    ACTIONS(79), 1,
      sym_doc,
    STATE(47), 1,
      aux_sym__item_repeat1,
    STATE(83), 1,
      sym_ident,
    STATE(10), 2,
      sym_field,
      aux_sym_struct_repeat1,
  [209] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      aux_sym_ident_token1,
    ACTIONS(79), 1,
      sym_doc,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    STATE(47), 1,
      aux_sym__item_repeat1,
    STATE(83), 1,
      sym_ident,
    STATE(14), 2,
      sym_field,
      aux_sym_struct_repeat1,
  [232] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 1,
      aux_sym_ident_token1,
    ACTIONS(87), 1,
      sym_doc,
    STATE(12), 1,
      sym_ident,
    STATE(52), 1,
      aux_sym__item_repeat1,
    STATE(13), 2,
      sym_variant,
      aux_sym_enum_repeat1,
  [255] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    STATE(45), 1,
      sym_variant_fields,
    STATE(46), 1,
      sym_unnamed_fields,
    ACTIONS(91), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [276] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_ident_token1,
    ACTIONS(87), 1,
      sym_doc,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_ident,
    STATE(52), 1,
      aux_sym__item_repeat1,
    STATE(18), 2,
      sym_variant,
      aux_sym_enum_repeat1,
  [299] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    ACTIONS(99), 1,
      aux_sym_ident_token1,
    ACTIONS(102), 1,
      sym_doc,
    STATE(47), 1,
      aux_sym__item_repeat1,
    STATE(83), 1,
      sym_ident,
    STATE(14), 2,
      sym_field,
      aux_sym_struct_repeat1,
  [322] = 8,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LBRACK,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    ACTIONS(109), 1,
      aux_sym_ident_token1,
    ACTIONS(111), 1,
      anon_sym_option,
    ACTIONS(113), 1,
      anon_sym_map,
    STATE(19), 1,
      aux_sym_service_repeat1,
    STATE(21), 1,
      sym_type,
  [347] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      sym_unnamed_fields,
    STATE(53), 1,
      sym_variant_fields,
    ACTIONS(117), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [368] = 8,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      aux_sym_ident_token1,
    ACTIONS(111), 1,
      anon_sym_option,
    ACTIONS(113), 1,
      anon_sym_map,
    ACTIONS(119), 1,
      anon_sym_RBRACK,
    STATE(20), 1,
      aux_sym_service_repeat1,
    STATE(21), 1,
      sym_type,
  [393] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 1,
      aux_sym_ident_token1,
    ACTIONS(126), 1,
      sym_doc,
    STATE(12), 1,
      sym_ident,
    STATE(52), 1,
      aux_sym__item_repeat1,
    STATE(18), 2,
      sym_variant,
      aux_sym_enum_repeat1,
  [416] = 8,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      aux_sym_ident_token1,
    ACTIONS(111), 1,
      anon_sym_option,
    ACTIONS(113), 1,
      anon_sym_map,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    STATE(5), 1,
      aux_sym_service_repeat1,
    STATE(21), 1,
      sym_type,
  [441] = 8,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      aux_sym_ident_token1,
    ACTIONS(111), 1,
      anon_sym_option,
    ACTIONS(113), 1,
      anon_sym_map,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
    STATE(5), 1,
      aux_sym_service_repeat1,
    STATE(21), 1,
      sym_type,
  [466] = 4,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(133), 3,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    ACTIONS(137), 3,
      aux_sym_ident_token1,
      anon_sym_option,
      anon_sym_map,
  [483] = 3,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(141), 3,
      aux_sym_ident_token1,
      anon_sym_option,
      anon_sym_map,
    ACTIONS(139), 4,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [498] = 3,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(145), 3,
      aux_sym_ident_token1,
      anon_sym_option,
      anon_sym_map,
    ACTIONS(143), 4,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [513] = 3,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(149), 3,
      aux_sym_ident_token1,
      anon_sym_option,
      anon_sym_map,
    ACTIONS(147), 4,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [528] = 3,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(153), 3,
      aux_sym_ident_token1,
      anon_sym_option,
      anon_sym_map,
    ACTIONS(151), 4,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [543] = 3,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(41), 3,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    ACTIONS(155), 3,
      aux_sym_ident_token1,
      anon_sym_option,
      anon_sym_map,
  [557] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [569] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [581] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [593] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [605] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [617] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [629] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_doc,
    STATE(33), 1,
      aux_sym__item_repeat1,
    ACTIONS(169), 4,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
  [645] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [657] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [669] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 6,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      anon_sym_enum,
      sym_doc,
  [681] = 6,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    ACTIONS(182), 1,
      aux_sym_ident_token1,
    ACTIONS(184), 1,
      anon_sym_option,
    ACTIONS(186), 1,
      anon_sym_map,
    STATE(43), 1,
      sym_type,
  [700] = 6,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    ACTIONS(182), 1,
      aux_sym_ident_token1,
    ACTIONS(184), 1,
      anon_sym_option,
    ACTIONS(186), 1,
      anon_sym_map,
    STATE(54), 1,
      sym_type,
  [719] = 6,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LBRACK,
    ACTIONS(190), 1,
      aux_sym_ident_token1,
    ACTIONS(192), 1,
      anon_sym_option,
    ACTIONS(194), 1,
      anon_sym_map,
    STATE(51), 1,
      sym_type,
  [738] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 5,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      aux_sym_ident_token1,
      sym_doc,
  [749] = 6,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LBRACK,
    ACTIONS(190), 1,
      aux_sym_ident_token1,
    ACTIONS(192), 1,
      anon_sym_option,
    ACTIONS(194), 1,
      anon_sym_map,
    STATE(48), 1,
      sym_type,
  [768] = 6,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LBRACK,
    ACTIONS(190), 1,
      aux_sym_ident_token1,
    ACTIONS(192), 1,
      anon_sym_option,
    ACTIONS(194), 1,
      anon_sym_map,
    STATE(49), 1,
      sym_type,
  [787] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(200), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [799] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(139), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [809] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    ACTIONS(117), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [821] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [831] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      aux_sym_ident_token1,
    ACTIONS(204), 1,
      sym_doc,
    STATE(67), 1,
      aux_sym__item_repeat1,
    STATE(96), 1,
      sym_ident,
  [847] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(206), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [857] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(208), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [867] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [877] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(212), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [887] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_ident_token1,
    ACTIONS(204), 1,
      sym_doc,
    STATE(16), 1,
      sym_ident,
    STATE(67), 1,
      aux_sym__item_repeat1,
  [903] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    ACTIONS(216), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [915] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_COMMA,
    ACTIONS(220), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [927] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [937] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(147), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [947] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(151), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [957] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(143), 4,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
      anon_sym_error,
  [967] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [977] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [987] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [997] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [1007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [1016] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [1025] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [1034] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [1043] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      aux_sym_ident_token1,
    ACTIONS(226), 1,
      sym_doc,
    STATE(67), 1,
      aux_sym__item_repeat1,
  [1056] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 3,
      anon_sym_RBRACE,
      aux_sym_ident_token1,
      sym_doc,
  [1065] = 3,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(77), 1,
      aux_sym_ident_token1,
    STATE(82), 1,
      sym_ident,
  [1075] = 3,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(77), 1,
      aux_sym_ident_token1,
    STATE(92), 1,
      sym_ident,
  [1085] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(196), 2,
      anon_sym_LBRACE,
      anon_sym_COLON,
  [1093] = 3,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(77), 1,
      aux_sym_ident_token1,
    STATE(95), 1,
      sym_ident,
  [1103] = 3,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(77), 1,
      aux_sym_ident_token1,
    STATE(76), 1,
      sym_ident,
  [1113] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LT,
  [1120] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_operations,
  [1127] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
  [1134] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_LT,
  [1141] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
  [1148] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_LT,
  [1155] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_GT,
  [1162] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_COMMA,
  [1169] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LBRACE,
  [1176] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_COLON,
  [1183] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_RBRACE,
  [1190] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(253), 1,
      aux_sym_ident_token1,
  [1197] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_GT,
  [1204] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
  [1211] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_RBRACK,
  [1218] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(261), 1,
      aux_sym_ident_token1,
  [1225] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(263), 1,
      aux_sym_ident_token1,
  [1232] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_COLON,
  [1239] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_LBRACE,
  [1246] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_LBRACK,
  [1253] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(271), 1,
      aux_sym_ident_token1,
  [1260] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_LBRACE,
  [1267] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_COLON,
  [1274] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_COLON,
  [1281] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_RBRACK,
  [1288] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_GT,
  [1295] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_GT,
  [1302] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_RBRACK,
  [1309] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_GT,
  [1316] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_GT,
  [1323] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(291), 1,
      aux_sym_ident_token1,
  [1330] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(293), 1,
      aux_sym_ident_token1,
  [1337] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(295), 1,
      aux_sym_ident_token1,
  [1344] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(297), 1,
      aux_sym_ident_token1,
  [1351] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(299), 1,
      aux_sym_ident_token1,
  [1358] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(301), 1,
      aux_sym_ident_token1,
  [1365] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_COLON,
  [1372] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_COMMA,
  [1379] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_LT,
  [1386] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(309), 1,
      anon_sym_COMMA,
  [1393] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(311), 1,
      aux_sym_ident_token1,
  [1400] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(313), 1,
      aux_sym_ident_token1,
  [1407] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_LT,
  [1414] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_LT,
  [1421] = 2,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 94,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 142,
  [SMALL_STATE(8)] = 164,
  [SMALL_STATE(9)] = 186,
  [SMALL_STATE(10)] = 209,
  [SMALL_STATE(11)] = 232,
  [SMALL_STATE(12)] = 255,
  [SMALL_STATE(13)] = 276,
  [SMALL_STATE(14)] = 299,
  [SMALL_STATE(15)] = 322,
  [SMALL_STATE(16)] = 347,
  [SMALL_STATE(17)] = 368,
  [SMALL_STATE(18)] = 393,
  [SMALL_STATE(19)] = 416,
  [SMALL_STATE(20)] = 441,
  [SMALL_STATE(21)] = 466,
  [SMALL_STATE(22)] = 483,
  [SMALL_STATE(23)] = 498,
  [SMALL_STATE(24)] = 513,
  [SMALL_STATE(25)] = 528,
  [SMALL_STATE(26)] = 543,
  [SMALL_STATE(27)] = 557,
  [SMALL_STATE(28)] = 569,
  [SMALL_STATE(29)] = 581,
  [SMALL_STATE(30)] = 593,
  [SMALL_STATE(31)] = 605,
  [SMALL_STATE(32)] = 617,
  [SMALL_STATE(33)] = 629,
  [SMALL_STATE(34)] = 645,
  [SMALL_STATE(35)] = 657,
  [SMALL_STATE(36)] = 669,
  [SMALL_STATE(37)] = 681,
  [SMALL_STATE(38)] = 700,
  [SMALL_STATE(39)] = 719,
  [SMALL_STATE(40)] = 738,
  [SMALL_STATE(41)] = 749,
  [SMALL_STATE(42)] = 768,
  [SMALL_STATE(43)] = 787,
  [SMALL_STATE(44)] = 799,
  [SMALL_STATE(45)] = 809,
  [SMALL_STATE(46)] = 821,
  [SMALL_STATE(47)] = 831,
  [SMALL_STATE(48)] = 847,
  [SMALL_STATE(49)] = 857,
  [SMALL_STATE(50)] = 867,
  [SMALL_STATE(51)] = 877,
  [SMALL_STATE(52)] = 887,
  [SMALL_STATE(53)] = 903,
  [SMALL_STATE(54)] = 915,
  [SMALL_STATE(55)] = 927,
  [SMALL_STATE(56)] = 937,
  [SMALL_STATE(57)] = 947,
  [SMALL_STATE(58)] = 957,
  [SMALL_STATE(59)] = 967,
  [SMALL_STATE(60)] = 977,
  [SMALL_STATE(61)] = 987,
  [SMALL_STATE(62)] = 997,
  [SMALL_STATE(63)] = 1007,
  [SMALL_STATE(64)] = 1016,
  [SMALL_STATE(65)] = 1025,
  [SMALL_STATE(66)] = 1034,
  [SMALL_STATE(67)] = 1043,
  [SMALL_STATE(68)] = 1056,
  [SMALL_STATE(69)] = 1065,
  [SMALL_STATE(70)] = 1075,
  [SMALL_STATE(71)] = 1085,
  [SMALL_STATE(72)] = 1093,
  [SMALL_STATE(73)] = 1103,
  [SMALL_STATE(74)] = 1113,
  [SMALL_STATE(75)] = 1120,
  [SMALL_STATE(76)] = 1127,
  [SMALL_STATE(77)] = 1134,
  [SMALL_STATE(78)] = 1141,
  [SMALL_STATE(79)] = 1148,
  [SMALL_STATE(80)] = 1155,
  [SMALL_STATE(81)] = 1162,
  [SMALL_STATE(82)] = 1169,
  [SMALL_STATE(83)] = 1176,
  [SMALL_STATE(84)] = 1183,
  [SMALL_STATE(85)] = 1190,
  [SMALL_STATE(86)] = 1197,
  [SMALL_STATE(87)] = 1204,
  [SMALL_STATE(88)] = 1211,
  [SMALL_STATE(89)] = 1218,
  [SMALL_STATE(90)] = 1225,
  [SMALL_STATE(91)] = 1232,
  [SMALL_STATE(92)] = 1239,
  [SMALL_STATE(93)] = 1246,
  [SMALL_STATE(94)] = 1253,
  [SMALL_STATE(95)] = 1260,
  [SMALL_STATE(96)] = 1267,
  [SMALL_STATE(97)] = 1274,
  [SMALL_STATE(98)] = 1281,
  [SMALL_STATE(99)] = 1288,
  [SMALL_STATE(100)] = 1295,
  [SMALL_STATE(101)] = 1302,
  [SMALL_STATE(102)] = 1309,
  [SMALL_STATE(103)] = 1316,
  [SMALL_STATE(104)] = 1323,
  [SMALL_STATE(105)] = 1330,
  [SMALL_STATE(106)] = 1337,
  [SMALL_STATE(107)] = 1344,
  [SMALL_STATE(108)] = 1351,
  [SMALL_STATE(109)] = 1358,
  [SMALL_STATE(110)] = 1365,
  [SMALL_STATE(111)] = 1372,
  [SMALL_STATE(112)] = 1379,
  [SMALL_STATE(113)] = 1386,
  [SMALL_STATE(114)] = 1393,
  [SMALL_STATE(115)] = 1400,
  [SMALL_STATE(116)] = 1407,
  [SMALL_STATE(117)] = 1414,
  [SMALL_STATE(118)] = 1421,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operation_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operation_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operation_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operation_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_service_repeat1, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 4, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 6, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 6, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 9, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 5, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__item_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__item_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 8, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 4, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 5, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ident, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_fields, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output, 3, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 3, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unnamed_fields, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 3, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unnamed_fields, 3, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 4, 0, 0),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__item_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 5, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [257] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lockstep(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lockstep",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
