/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_service = 1,
  anon_sym_LBRACE = 2,
  anon_sym_operations = 3,
  anon_sym_COLON = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  anon_sym_RBRACE = 7,
  anon_sym_operation = 8,
  anon_sym_input = 9,
  anon_sym_output = 10,
  anon_sym_struct = 11,
  anon_sym_COMMA = 12,
  sym_ident = 13,
  sym_comment = 14,
  sym_doc = 15,
  sym_file = 16,
  sym__item = 17,
  sym_service = 18,
  sym_operation = 19,
  sym_input = 20,
  sym_output = 21,
  sym_struct = 22,
  sym_field = 23,
  sym_type = 24,
  aux_sym_file_repeat1 = 25,
  aux_sym__item_repeat1 = 26,
  aux_sym_service_repeat1 = 27,
  aux_sym_operation_repeat1 = 28,
  aux_sym_struct_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_service] = "service",
  [anon_sym_LBRACE] = "{",
  [anon_sym_operations] = "operations",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_RBRACE] = "}",
  [anon_sym_operation] = "operation",
  [anon_sym_input] = "input",
  [anon_sym_output] = "output",
  [anon_sym_struct] = "struct",
  [anon_sym_COMMA] = ",",
  [sym_ident] = "ident",
  [sym_comment] = "comment",
  [sym_doc] = "doc",
  [sym_file] = "file",
  [sym__item] = "_item",
  [sym_service] = "service",
  [sym_operation] = "operation",
  [sym_input] = "input",
  [sym_output] = "output",
  [sym_struct] = "struct",
  [sym_field] = "field",
  [sym_type] = "type",
  [aux_sym_file_repeat1] = "file_repeat1",
  [aux_sym__item_repeat1] = "_item_repeat1",
  [aux_sym_service_repeat1] = "service_repeat1",
  [aux_sym_operation_repeat1] = "operation_repeat1",
  [aux_sym_struct_repeat1] = "struct_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_service] = anon_sym_service,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_operations] = anon_sym_operations,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_operation] = anon_sym_operation,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_output] = anon_sym_output,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_ident] = sym_ident,
  [sym_comment] = sym_comment,
  [sym_doc] = sym_doc,
  [sym_file] = sym_file,
  [sym__item] = sym__item,
  [sym_service] = sym_service,
  [sym_operation] = sym_operation,
  [sym_input] = sym_input,
  [sym_output] = sym_output,
  [sym_struct] = sym_struct,
  [sym_field] = sym_field,
  [sym_type] = sym_type,
  [aux_sym_file_repeat1] = aux_sym_file_repeat1,
  [aux_sym__item_repeat1] = aux_sym__item_repeat1,
  [aux_sym_service_repeat1] = aux_sym_service_repeat1,
  [aux_sym_operation_repeat1] = aux_sym_operation_repeat1,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_service] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_operations] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_operation] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_output] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_doc] = {
    .visible = true,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_service] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [sym_output] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_service_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 11,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 21,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 22,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 44,
  [57] = 50,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        ',', 54,
        '/', 2,
        ':', 46,
        '[', 47,
        ']', 48,
        'i', 16,
        'o', 21,
        's', 9,
        '{', 44,
        '}', 49,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ',') ADVANCE(54);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '}') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(56);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(57);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(25);
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(11);
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == 'p') ADVANCE(38);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(12);
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 39:
      if (lookahead == 'v') ADVANCE(14);
      END_STATE();
    case 40:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 41:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '/', 3,
        ':', 46,
        '[', 47,
        ']', 48,
        'i', 16,
        'o', 24,
        '{', 44,
        '}', 49,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_service);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_operations);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_operation);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_output);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '/') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_doc);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(58);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 41},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 41},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 41},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 41},
  [30] = {.lex_state = 41},
  [31] = {.lex_state = 41},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 41},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 41},
  [39] = {.lex_state = 41},
  [40] = {.lex_state = 41},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 41},
  [43] = {.lex_state = 41},
  [44] = {.lex_state = 41},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 41},
  [47] = {.lex_state = 41},
  [48] = {.lex_state = 41},
  [49] = {.lex_state = 41},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 41},
  [52] = {.lex_state = 41},
  [53] = {.lex_state = 41},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 41},
  [56] = {.lex_state = 41},
  [57] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_service] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_operation] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_output] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_doc] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_file] = STATE(39),
    [sym__item] = STATE(2),
    [sym_service] = STATE(2),
    [sym_operation] = STATE(2),
    [sym_struct] = STATE(2),
    [aux_sym_file_repeat1] = STATE(2),
    [aux_sym__item_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_service] = ACTIONS(7),
    [anon_sym_operation] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
    [sym_doc] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_service,
    ACTIONS(9), 1,
      anon_sym_operation,
    ACTIONS(11), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      sym_doc,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      aux_sym__item_repeat1,
    STATE(3), 5,
      sym__item,
      sym_service,
      sym_operation,
      sym_struct,
      aux_sym_file_repeat1,
  [29] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_service,
    ACTIONS(22), 1,
      anon_sym_operation,
    ACTIONS(25), 1,
      anon_sym_struct,
    ACTIONS(28), 1,
      sym_doc,
    STATE(4), 1,
      aux_sym__item_repeat1,
    STATE(3), 5,
      sym__item,
      sym_service,
      sym_operation,
      sym_struct,
      aux_sym_file_repeat1,
  [58] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_service,
    ACTIONS(9), 1,
      anon_sym_operation,
    ACTIONS(11), 1,
      anon_sym_struct,
    ACTIONS(31), 1,
      sym_doc,
    STATE(11), 1,
      aux_sym__item_repeat1,
    STATE(12), 3,
      sym_service,
      sym_operation,
      sym_struct,
  [82] = 5,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 1,
      anon_sym_input,
    ACTIONS(37), 1,
      anon_sym_output,
    ACTIONS(39), 1,
      sym_comment,
    STATE(7), 3,
      sym_input,
      sym_output,
      aux_sym_operation_repeat1,
  [100] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 1,
      sym_ident,
    ACTIONS(45), 1,
      sym_doc,
    STATE(37), 1,
      aux_sym__item_repeat1,
    STATE(9), 2,
      sym_field,
      aux_sym_struct_repeat1,
  [120] = 5,
    ACTIONS(35), 1,
      anon_sym_input,
    ACTIONS(37), 1,
      anon_sym_output,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(10), 3,
      sym_input,
      sym_output,
      aux_sym_operation_repeat1,
  [138] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      sym_ident,
    ACTIONS(54), 1,
      sym_doc,
    STATE(37), 1,
      aux_sym__item_repeat1,
    STATE(8), 2,
      sym_field,
      aux_sym_struct_repeat1,
  [158] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_ident,
    ACTIONS(45), 1,
      sym_doc,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      aux_sym__item_repeat1,
    STATE(8), 2,
      sym_field,
      aux_sym_struct_repeat1,
  [178] = 5,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    ACTIONS(61), 1,
      anon_sym_input,
    ACTIONS(64), 1,
      anon_sym_output,
    STATE(10), 3,
      sym_input,
      sym_output,
      aux_sym_operation_repeat1,
  [196] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_doc,
    STATE(11), 1,
      aux_sym__item_repeat1,
    ACTIONS(67), 3,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
  [211] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      sym_doc,
  [222] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 5,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      sym_doc,
  [233] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 5,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      sym_doc,
  [244] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 5,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      sym_doc,
  [255] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 5,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      sym_doc,
  [266] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 5,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      sym_doc,
  [277] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 5,
      ts_builtin_sym_end,
      anon_sym_service,
      anon_sym_operation,
      anon_sym_struct,
      sym_doc,
  [288] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(86), 3,
      anon_sym_RBRACE,
      sym_ident,
      sym_doc,
  [300] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_COMMA,
    ACTIONS(90), 3,
      anon_sym_RBRACE,
      sym_ident,
      sym_doc,
  [312] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_ident,
      sym_doc,
  [322] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_ident,
      sym_doc,
  [332] = 4,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_RBRACK,
    ACTIONS(100), 1,
      sym_ident,
    STATE(23), 1,
      aux_sym_service_repeat1,
  [345] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      sym_ident,
    ACTIONS(103), 1,
      sym_doc,
    STATE(24), 1,
      aux_sym__item_repeat1,
  [358] = 4,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_LBRACK,
    ACTIONS(108), 1,
      sym_ident,
    STATE(30), 1,
      sym_type,
  [371] = 4,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_LBRACK,
    ACTIONS(108), 1,
      sym_ident,
    STATE(31), 1,
      sym_type,
  [384] = 4,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_LBRACK,
    ACTIONS(112), 1,
      sym_ident,
    STATE(19), 1,
      sym_type,
  [397] = 4,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_RBRACK,
    ACTIONS(116), 1,
      sym_ident,
    STATE(33), 1,
      aux_sym_service_repeat1,
  [410] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(94), 3,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
  [419] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(118), 3,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
  [428] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(120), 3,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
  [437] = 4,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_LBRACK,
    ACTIONS(112), 1,
      sym_ident,
    STATE(20), 1,
      sym_type,
  [450] = 4,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_RBRACK,
    ACTIONS(124), 1,
      sym_ident,
    STATE(23), 1,
      aux_sym_service_repeat1,
  [463] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 3,
      anon_sym_RBRACE,
      sym_ident,
      sym_doc,
  [472] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(96), 3,
      anon_sym_RBRACE,
      anon_sym_input,
      anon_sym_output,
  [481] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 3,
      anon_sym_RBRACE,
      sym_ident,
      sym_doc,
  [490] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      sym_ident,
    ACTIONS(130), 1,
      sym_doc,
    STATE(24), 1,
      aux_sym__item_repeat1,
  [503] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
  [510] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
  [517] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_COLON,
  [524] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(138), 1,
      sym_ident,
  [531] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
  [538] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
  [545] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_RBRACK,
  [552] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(146), 1,
      sym_ident,
  [559] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_LBRACE,
  [566] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_COLON,
  [573] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
  [580] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_COLON,
  [587] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym_ident,
  [594] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_operations,
  [601] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
  [608] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_COLON,
  [615] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(164), 1,
      sym_ident,
  [622] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_COLON,
  [629] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_RBRACK,
  [636] = 2,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(170), 1,
      sym_ident,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 82,
  [SMALL_STATE(6)] = 100,
  [SMALL_STATE(7)] = 120,
  [SMALL_STATE(8)] = 138,
  [SMALL_STATE(9)] = 158,
  [SMALL_STATE(10)] = 178,
  [SMALL_STATE(11)] = 196,
  [SMALL_STATE(12)] = 211,
  [SMALL_STATE(13)] = 222,
  [SMALL_STATE(14)] = 233,
  [SMALL_STATE(15)] = 244,
  [SMALL_STATE(16)] = 255,
  [SMALL_STATE(17)] = 266,
  [SMALL_STATE(18)] = 277,
  [SMALL_STATE(19)] = 288,
  [SMALL_STATE(20)] = 300,
  [SMALL_STATE(21)] = 312,
  [SMALL_STATE(22)] = 322,
  [SMALL_STATE(23)] = 332,
  [SMALL_STATE(24)] = 345,
  [SMALL_STATE(25)] = 358,
  [SMALL_STATE(26)] = 371,
  [SMALL_STATE(27)] = 384,
  [SMALL_STATE(28)] = 397,
  [SMALL_STATE(29)] = 410,
  [SMALL_STATE(30)] = 419,
  [SMALL_STATE(31)] = 428,
  [SMALL_STATE(32)] = 437,
  [SMALL_STATE(33)] = 450,
  [SMALL_STATE(34)] = 463,
  [SMALL_STATE(35)] = 472,
  [SMALL_STATE(36)] = 481,
  [SMALL_STATE(37)] = 490,
  [SMALL_STATE(38)] = 503,
  [SMALL_STATE(39)] = 510,
  [SMALL_STATE(40)] = 517,
  [SMALL_STATE(41)] = 524,
  [SMALL_STATE(42)] = 531,
  [SMALL_STATE(43)] = 538,
  [SMALL_STATE(44)] = 545,
  [SMALL_STATE(45)] = 552,
  [SMALL_STATE(46)] = 559,
  [SMALL_STATE(47)] = 566,
  [SMALL_STATE(48)] = 573,
  [SMALL_STATE(49)] = 580,
  [SMALL_STATE(50)] = 587,
  [SMALL_STATE(51)] = 594,
  [SMALL_STATE(52)] = 601,
  [SMALL_STATE(53)] = 608,
  [SMALL_STATE(54)] = 615,
  [SMALL_STATE(55)] = 622,
  [SMALL_STATE(56)] = 629,
  [SMALL_STATE(57)] = 636,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_operation_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operation_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_operation_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__item_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__item_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 5, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 8, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 9, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__item_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 5, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [134] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lockstep(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lockstep",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
